export const LIST_ALL_COFFEES_REQUEST = ' LIST_ALL_COFFEES_REQUEST';
export const  LIST_ALL_COFFEES_FAIL = ' LIST_ALL_COFFEES_FAIL';
export const  LIST_ALL_COFFEES_SUCCESS = ' LIST_ALL_COFFEES_SUCCESS';


export const COFFEE_WINDOW_REQUEST = 'COFFEE_WINDOW_REQUEST';
export const COFFEE_WINDOW_FAIL = 'COFFEE_WINDOW_FAIL';
export const COFFEE_WINDOW_SUCCESS = 'COFFEE_WINDOW_SUCCESS';
export const COFFEE_WINDOW_RESET = 'COFFEE_WINDOW_RESET';


export const  CREATE_COFFEE_REQUEST = 'CREATE_COFFEE_REQUEST ';
export const  CREATE_COFFEE_SUCCESS = 'CREATE_COFFEE_SUCCESS ';
export const  CREATE_COFFEE_FAIL= 'CREATE_COFFEE_FAIL ';
export const  CREATE_COFFEE_RESET= 'CREATE_COFFEE_RESET ';


export const  COFFEE_INFO_REQUEST = 'COFFEE_INFO_REQUEST';
export const  COFFEE_INFO_SUCCESS = 'COFFEE_INFO_SUCCESS';
export const  COFFEE_INFO_FAIL = 'COFFEE_INFO_FAIL';

export const  UPDATE_COFFEE_REQUEST = 'UPDATE_COFFEE_REQUEST';
export const  UPDATE_COFFEE_SUCCESS = 'UPDATE_COFFEE_SUCCESS';
export const  UPDATE_COFFEE_FAIL = 'UPDATE_COFFEE_FAIL';


export const DELETE_COFFEE_REQUEST = 'DELETE_COFFEE_REQUEST'
export const DELETE_COFFEE_SUCCESS  = 'DELETE_COFFEE_SUCCESS'
export const DELETE_COFFEE_FAIL  = 'DELETE_COFFEE_FAIL'
export const DELETE_COFFEE_RESET = 'DELETE_COFFEE_FAIL'

export const COFFEE_LIST_SEARCH_REQUEST = 'COFFEE_LIST_SEARCH_REQUEST'
export const COFFEE_LIST_SEARCH_SUCCESS = 'COFFEE_LIST_SEARCH_SUCCESS'
export const COFFEE_LIST_SEARCH_FAIL = 'COFFEE_LIST_SEARCH_FAIL'

export const LIST_ALL_CATEGORY_REQUEST = 'LIST_ALL_CATEGORY_REQUEST';
export const LIST_ALL_CATEGORY_SUCCESS = 'LIST_ALL_CATEGORY_SUCCESS';
export const LIST_ALL_CATEGORY_FAIL = 'LIST_ALL_CATEGORY_FAIL';


export const CATEGORY_LIST_SEARCH_REQUEST = 'CATEGORY_LIST_SEARCH_REQUEST';
export const CATEGORY_LIST_SEARCH_SUCCESS = 'CATEGORY_LIST_SEARCH_SUCCESS';
export const CATEGORY_LIST_SEARCH_FAIL = 'CATEGORY_LIST_SEARCH_FAIL';


export const COFFEE_LIST_SORT_REQUEST = 'COFFEE_LIST_SORT_REQUEST';
export const COFFEE_LIST_SORT_SUCCESS= 'COFFEE_LIST_SORT_SUCCESS';
export const COFFEE_LIST_SORT_FAIL = 'COFFEE_LIST_SORT_FAIL';

export const COFFEE_LIST_SORT_LOW = 'COFFEE_LIST_SORT_LOW';
export const COFFEE_LIST_SORT_HIGH = 'COFFEE_LIST_SORT_HIGH';
export const COFFEE_LIST_SORT_NEW = 'COFFEE_LIST_SORT_NEW';
export const COFFEE_LIST_SORT_OLD = 'COFFEE_LIST_SORT_OLD';


export const LIST_ALL_ADMIN_COFFEES_REQUEST = 'LIST_ALL_ADMIN_COFFEES_REQUEST';
export const LIST_ALL_ADMIN_COFFEES_SUCCESS = 'LIST_ALL_ADMIN_COFFEES_SUCCESS';
export const LIST_ALL_ADMIN_COFFEES_FAIL = 'LIST_ALL_ADMIN_COFFEES_FAIL';
export const LIST_ALL_ADMIN_COFFEES_RESET = 'LIST_ALL_ADMIN_COFFEES_RESET';