export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';
export const ORDER_DELETE_TERMS = 'ORDER_DELETE_TERMS';

export const ORDER_PAYMENT_REQUEST = 'ORDER_PAY_REQUEST';
export const ORDER_PAYMENT_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAYMENT_FAIL = 'ORDER_PAY_FAIL';
export const ORDER_PAYMENT_RESET = 'ORDER_PAY_RESET';

export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST';
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS';
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL';
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const ORDER_USER_HISTORY_LIST_REQUEST = 'ORDER_USER_HISTORY_LIST_REQUEST';
export const ORDER_USER_HISTORY_LIST_SUCCESS = 'ORDER_USER_HISTORY_LIST_SUCCESS';
export const ORDER_USER_HISTORY_LIST_FAIL = 'ORDER_USER_HISTORY_LIST_FAIL';

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';


export const LIST_ORDER_USER_REQUEST = 'LIST_ORDER_USER_REQUEST';
export const LIST_ORDER_USER_SUCCESS = 'LIST_ORDER_USER_SUCCESS';
export const LIST_ORDER_USER_FAIL = 'LIST_ORDER_USER_FAIL';

export const ORDER_DELETE_TERMS_SUCCESS = ' ORDER_DELETE_TERMS_SUCCESS';

export const LIST_ALL_ORDERS_REQUEST = 'LIST_ALL_ORDERS_REQUEST';
export const LIST_ALL_ORDERS_SUCCESS = 'LIST_ALL_ORDERS_SUCCESS';
export const LIST_ALL_ORDERS_FAIL = 'LIST_ALL_ORDERS_FAIL';
export const LIST_ALL_ORDERS_RESET = 'LIST_ALL_ORDERS_RESET';

export const DELETE_ORDER_REQUEST = 'DELETE_ORDER_REQUEST';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAIL = 'DELETE_ORDER_FAIL';
export const DELETE_ORDER_RESET = 'DELETE_ORDER_RESET';


export const TAKEBACK_ORDER_REQUEST = 'ACCEPT_ORDER_REQUEST';
export const TAKEBACK_ORDER_SUCCESS = 'ACCEPT_ORDER_SUCCESS';
export const TAKEBACK_ORDER_FAIL = 'ACCEPT_ORDER_FAIL';
export const TAKEBACK_ORDER_RESET ='ACCEPT_ORDER_RESET;'