export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SET_USER = 'SET_USER';
export const LOGOUT = 'LOGOUT';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const USER_PROFILE_UPDATE_REQUEST = 'USER_PROFILE_UPDATE_REQUEST';
export const USER_PROFILE_UPDATE_SUCCESS = 'USER_PROFILE_UPDATE_SUCCESS';
export const USER_PROFILE_UPDATE_FAIL = 'USER_PROFILE_UPDATE_FAIL';

export const USER_PERSONAL_DATA_UPDATE_REQUEST = "USER_PERSONAL_DATA_UPDATE_REQUEST";
export const USER_PERSONAL_DATA_UPDATE_SUCCESS = "USER_PERSONAL_DATA_UPDATE_SUCCESS";
export const USER_PERSONAL_DATA_UPDATE_FAIL = "USER_PERSONAL_DATA_UPDATE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const LIST_ALL_USERS_REQUEST = 'LIST_ALL_USERS_REQUEST';
export const LIST_ALL_USERS_SUCCESS = 'LIST_ALL_USERS_SUCCESS';
export const LIST_ALL_USERS_FAIL = 'LIST_ALL_USERS_FAIL';
export const LIST_ALL_USERS_RESET = 'LIST_ALL_USERS_RESET';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS= 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
export const DELETE_USER_RESET = 'DELETE_USER_RESET';

export const CONTACT_MESSAGE_SENT = 'CONTACT_MESSAGE_SENT';

export const LIST_ALL_CONTACT_MESSAGES_REQUEST ='LIST_ALL_CONTACT_MESSAGES_REQUEST';
export const LIST_ALL_CONTACT_MESSAGES_SUCCESS ='LIST_ALL_CONTACT_MESSAGES_SUCCESS';
export const LIST_ALL_CONTACT_MESSAGES_FAIL ='LIST_ALL_CONTACT_MESSAGES_FAIL';
export const LIST_ALL_CONTACT_MESSAGES_RESET = 'LIST_ALL_CONTACT_MESSAGES_RESET';

export const DELETE_MESSAGE_REQUEST = 'DELETE_MESSAGE_REQUEST';
export const DELETE_MESSAGE_SUCCESS= 'DELETE_MESSAGE_SUCCESS';
export const DELETE_MESSAGE_FAIL = 'DELETE_MESSAGE_FAIL';
export const DELETE_MESSAGE_RESET = 'DELETE_MESSAGE_RESET';


export const MESSAGE_WINDOW_REQUEST = 'MESSAGE_WINDOW_REQUEST';
export const MESSAGE_WINDOW_SUCCESS = 'MESSAGE_WINDOW_SUCCESS';
export const MESSAGE_WINDOW_FAIL = 'MESSAGE_WINDOW_FAIL';
export const MESSAGE_WINDOW_RESET = 'MESSAGE_WINDOW_RESET';

export const CONTACT_RESPOND_SENT = 'CONTACT_RESPOND_SENT';
export const CONTACT_RESPOND_RESET = 'CONTACT_RESPOND_RESET';
export const CONTACT_RESPOND_SUCCESS = 'CONTACT_RESPOND_SUCCESS';
export const CONTACT_RESPOND_FAIL = 'CONTACT_RESPOND_FAIL';

export const NEW_NEWSLETTER_APPLICATION = 'NEW_NEWSLETTER_APPLICATION';

export const ADMIN_SEARCH_REQUEST = 'ADMIN_SEARCH_REQUEST';
export const ADMIN_SEARCH_SUCCESS = 'ADMIN_SEARCH_SUCCESS';
export const ADMIN_SEARCH_FAIL= 'ADMIN_SEARCH_FAIL';
export const ADMIN_SEARCH_RESET = 'ADMIN_SEARCH_RESET';

export const LIST_ALL_ADMIN_COFFEES_REQUEST = 'LIST_ALL_ADMIN_COFFEES_REQUEST';
export const LIST_ALL_ADMIN_COFFEES_SUCCESS = 'LIST_ALL_ADMIN_COFFEES_SUCCESS';
export const LIST_ALL_ADMIN_COFFEES_FAIL = 'LIST_ALL_ADMIN_COFFEES_FAIL';
export const LIST_ALL_ADMIN_COFFEES_RESET = 'LIST_ALL_ADMIN_COFFEES_RESET';

export const ADMIN_SEARCH_ALL_COFFEES = 'ADMIN_SEARCH_ALL_COFFEES';
export const ADMIN_SEARCH_SUCCESS_ORDERS = 'ADMIN_SEARCH_SUCCESS_ORDERS';
export const ADMIN_SEARCH_USERS_SUCCESS = 'ADMIN_SEARCH_USERS_SUCCESS';
export const ADMIN_SEARCH_CONTACT_SUCCESS = 'ADMIN_SEARCH_CONTACT_SUCCESS';

export const CONTACT_LIST_SORT_NEW = 'CONTACT_LIST_SORT_NEW';
export const CONTACT_LIST_SORT_LAST = 'CONTACT_LIST_SORT_LAST';
export const CONTACT_LIST_SORT_FAIL = 'CONTACT_LIST_SORT_FAIL';

export const SET_SHIPPING_PRICE_SUCCESS = 'SET_SHIPPING_PRICE_SUCCESS';
export const SET_SHIPPING_PRICE_FAIL = 'SET_SHIPPING_PRICE_FAIL';






